package com.atvantiq.wfms.ui.screens.reimbursement.createClaim

enum class CreateClaimClickEvents {
    ON_DATE_PICKER_CLICK,
    ON_SINGLE_SITE_CLICK,
    ON_MULTI_SITE_CLICK,
    ON_LOCAL_CLAIM_CLICK,
    ON_OUTSTATION_CLAIM_CLICK,
    ON_ADD_MULTIPLE_SITE_CLICK,
    ON_SINGLE_SITE_DROPDOWN_CLICK,
    ON_ADD_TRAVELING_EXPENSE_CLICK,
    ON_ADD_DAILY_ALLOWANCE_CLICK,
    ON_ADD_HOTEL_EXPENSE_CLICK,
    ON_ADD_OTHERS_EXPENSE_CLICK,
    ON_CANCEL_CLICK,
    ON_PURPOSE_CLICK,
    ON_PROJECT_DROPDOWN_CLICK,
    ON_CIRCLE_DROPDOWN_CLICK,
}